//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceiptNoteDetail
    {
        public string ProductID { get; set; }
        public string GoodsReceiptNoteID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual GoodsReceiptNote GoodsReceiptNote { get; set; }
        public virtual Product Product { get; set; }
    }
}
